# Generated by Django 6.0 on 2026-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('SCHOOL', 'School'), ('NGO', 'NGO'), ('CHARITY', 'Charity'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='HOSPITAL', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
