# Generated by Django 5.1.4 on 2026-05-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_donation_id_alter_needitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='government_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
