# Generated by Django 5.1.4 on 2026-05-23 16:03

import django.db.models.deletion
from django.db import migrations, models


def copy_admin_users(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    for org in Organization.objects.all():
        if org.admin_user_id:
            user = User.objects.get(pk=org.admin_user_id)
            user.organization_id = org.pk
            user.save()

def reverse_copy_admin_users(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    for org in Organization.objects.all():
        # Just grab the first admin
        admin = User.objects.filter(organization_id=org.pk, role='ORG_ADMIN').first()
        if admin:
            org.admin_user_id = admin.pk
            org.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_donation_government_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this user is an admin for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='core.organization'),
        ),
        migrations.RunPython(copy_admin_users, reverse_copy_admin_users),
        migrations.RemoveField(
            model_name='organization',
            name='admin_user',
        ),
    ]
