# Generated by Django 5.1.4 on 2026-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_organization_latitude_organization_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
