# Generated by Django 6.0.3 on 2026-06-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_donation_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
