# Generated by Django 6.0.3 on 2026-06-13 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_donation_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
