# Generated by Django 5.1.4 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PLEDGE_CREATED', 'New Pledge Created'), ('PLEDGE_CONFIRMED', 'Pledge Confirmed'), ('PLEDGE_CANCELLED', 'Pledge Cancelled'), ('PLEDGE_RECEIVED', 'Pledge Marked Received'), ('ADMIN_APPROVAL_REQUEST', 'Org Admin Approval Request'), ('REGISTRATION_DECISION', 'Registration Request Actioned'), ('PLEDGE_REMINDER', 'Pledge Delivery Reminder')], max_length=30),
        ),
    ]
